// Knowledge Base static data

export const PLATFORMS = [
  {
    id: 'instagram',
    name: 'Instagram',
    emoji: '📸',
    color: 'from-pink-500 to-purple-600',
    badge: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    bestContentTypes: ['Reels (15-90s)', 'Carousels', 'Stories', 'Static posts', 'Collab posts'],
    bestIndustries: ['Fashion/Beauty', 'Food & Beverage', 'Fitness', 'Travel', 'E-commerce', 'Hospitality'],
    postingFrequency: '4-7x per week',
    peakTimes: 'Tue–Fri, 9am–11am & 6pm–9pm (local time)',
    avgEngagementRate: '0.5% – 3% (nano: up to 8%)',
    whatWorkingNow: [
      'Reels under 30s with hook in first 2 seconds',
      'Trending audio + original video combinations',
      'Educational carousels (save-worthy content)',
      'Authentic behind-the-scenes Stories',
      'Collab posts with complementary brands',
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    emoji: '🎵',
    color: 'from-gray-800 to-gray-900',
    badge: 'bg-gray-500/10 text-gray-300 border-gray-500/20',
    bestContentTypes: ['Short videos 15-60s', 'Duets', 'Stitches', 'TikTok Lives', 'Trending challenges'],
    bestIndustries: ['Fashion', 'Beauty/Skincare', 'Food', 'Fitness', 'Entertainment', 'Education', 'SaaS (B2C)'],
    postingFrequency: '1-4x per day',
    peakTimes: 'Tue–Sat, 7am–9am & 7pm–9pm',
    avgEngagementRate: '4% – 18% (highest of all platforms)',
    whatWorkingNow: [
      'POV and storytelling formats',
      'Day-in-the-life content',
      'Unboxing and reaction videos',
      'Educational "Did you know" hooks',
      'Behind-the-scenes business content',
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    emoji: '💼',
    color: 'from-blue-700 to-blue-800',
    badge: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    bestContentTypes: ['Text posts with hooks', 'Document carousels', 'Short videos', 'Polls', 'Newsletters'],
    bestIndustries: ['SaaS/Tech', 'Professional Services', 'Real Estate', 'Finance', 'Consulting', 'Healthcare', 'Construction'],
    postingFrequency: '3-5x per week',
    peakTimes: 'Tue–Thu, 7am–9am & 12pm–1pm',
    avgEngagementRate: '2% – 5% (organic reach is strong)',
    whatWorkingNow: [
      'Personal founder stories performing 3x better than brand posts',
      'Native document carousels (PDFs) for thought leadership',
      'Contrarian takes and hot opinions',
      'Case studies with real numbers',
      'Hiring/team culture posts for brand building',
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    emoji: '👥',
    color: 'from-blue-600 to-blue-700',
    badge: 'bg-blue-400/10 text-blue-300 border-blue-400/20',
    bestContentTypes: ['Video', 'Groups content', 'Events', 'Facebook Ads', 'Live video'],
    bestIndustries: ['Local Businesses', 'E-commerce', 'Real Estate', 'Healthcare', 'Food & Beverage', 'Construction/Trades'],
    postingFrequency: '3-5x per week',
    peakTimes: 'Wed–Fri, 1pm–4pm',
    avgEngagementRate: '0.08% – 0.7% (organic declining)',
    whatWorkingNow: [
      'Facebook Groups for community building',
      'Video content (native uploads vs YouTube links)',
      'Facebook Ads remain extremely effective for targeting',
      'Events for local businesses',
      'Retargeting campaigns for e-commerce',
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    emoji: '▶',
    color: 'from-red-600 to-red-700',
    badge: 'bg-red-500/10 text-red-400 border-red-500/20',
    bestContentTypes: ['Long-form tutorials', 'YouTube Shorts', 'Case studies', 'Reviews', 'Vlogs'],
    bestIndustries: ['Education', 'Tech/SaaS', 'Fitness', 'Finance', 'DIY/Construction', 'Gaming', 'Professional Services'],
    postingFrequency: '1-3x per week (long-form) + daily Shorts',
    peakTimes: 'Fri–Sun, 2pm–4pm (long-form), anytime (Shorts)',
    avgEngagementRate: '1% – 4% (Shorts: up to 10%)',
    whatWorkingNow: [
      'YouTube Shorts driving subscribers to long-form content',
      'SEO-optimised thumbnails (faces + text overlay)',
      'Episode-style series for return viewers',
      'Timestamps and chapters for retention',
      'Community posts to stay active between uploads',
    ],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    emoji: '✖',
    color: 'from-gray-700 to-gray-800',
    badge: 'bg-gray-400/10 text-gray-300 border-gray-400/20',
    bestContentTypes: ['Threads', 'Short takes', 'Polls', 'Spaces', 'Quote tweets'],
    bestIndustries: ['SaaS/Tech', 'Finance/Crypto', 'Media', 'Marketing', 'Politics', 'Sports'],
    postingFrequency: '3-7x per day',
    peakTimes: 'Mon–Fri, 8am–10am & 12pm–1pm',
    avgEngagementRate: '0.5% – 2%',
    whatWorkingNow: [
      'Long-form threads with actionable insights',
      'Real-time commentary on trending topics',
      'X Premium for content visibility boost',
      'Building in public journeys',
      'Short punchy takes under 140 characters',
    ],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    emoji: '📌',
    color: 'from-red-500 to-red-600',
    badge: 'bg-red-400/10 text-red-300 border-red-400/20',
    bestContentTypes: ['Idea pins', 'Static pins', 'Video pins', 'Infographics', 'Product pins'],
    bestIndustries: ['Home Decor', 'Fashion', 'Food/Recipes', 'Beauty', 'Wedding', 'DIY', 'Fitness'],
    postingFrequency: '3-5 pins per day',
    peakTimes: 'Sat–Sun evenings, weekday evenings',
    avgEngagementRate: '0.3% – 1% (but traffic-driving potential is very high)',
    whatWorkingNow: [
      'Idea Pins for top-of-funnel discovery',
      'SEO-rich pin descriptions with keywords',
      'Pinterest shopping catalogue integration',
      'Seasonal content planned 30-45 days early',
      'Consistent visual brand aesthetic',
    ],
  },
]

export const INDUSTRIES = [
  {
    id: 'ecommerce',
    name: 'E-commerce',
    emoji: '🛍',
    topPlatforms: ['Instagram', 'TikTok', 'Pinterest', 'Facebook'],
    contentStyle: 'Product showcases, UGC, unboxings, lifestyle photography, before/after',
    keyMetrics: 'ROAS (target 3-5x), CTR, conversion rate, abandoned cart rate',
    commonMistakes: [
      'Only posting product photos with no context or story',
      'Ignoring customer review content (UGC goldmine)',
      'No retargeting strategy for warm audiences',
      'Underusing Pinterest for product discovery',
    ],
    expectedResults: 'With consistent effort: 15-30% MoM follower growth, 2-4% engagement, 1.5-3% conversion on ads within 60 days',
  },
  {
    id: 'saas',
    name: 'SaaS / Tech',
    emoji: '💻',
    topPlatforms: ['LinkedIn', 'X/Twitter', 'YouTube', 'Reddit'],
    contentStyle: 'Educational content, product demos, founder thought leadership, case studies, ROI proof',
    keyMetrics: 'MQLs, trial signups, activation rate, CAC vs LTV',
    commonMistakes: [
      'Feature-focused content instead of outcome-focused',
      'Ignoring LinkedIn for B2B SaaS',
      'No customer success stories or case studies',
      'Missing SEO content strategy alongside social',
    ],
    expectedResults: 'With consistent effort: 2-5% organic traffic growth MoM, 10-20 inbound leads/month at 90 days',
  },
  {
    id: 'hospitality',
    name: 'Hospitality',
    emoji: '🏨',
    topPlatforms: ['Instagram', 'TikTok', 'Facebook', 'Google Business'],
    contentStyle: 'Atmosphere/ambiance videos, staff spotlights, food/drink showcases, events, guest reviews',
    keyMetrics: 'Table bookings, occupancy rate, review rating, repeat visit rate',
    commonMistakes: [
      'Not responding to Google/TripAdvisor reviews (signals trust)',
      'Poor quality food photography',
      'Not leveraging local hashtags and geo-tags',
      'Ignoring Stories for real-time specials and events',
    ],
    expectedResults: 'With consistent effort: 20-40% increase in direct bookings, 15-25% engagement rate on local content within 90 days',
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    emoji: '🏡',
    topPlatforms: ['Instagram', 'Facebook', 'YouTube', 'LinkedIn'],
    contentStyle: 'Property tours, market updates, buyer/seller tips, agent behind-the-scenes, testimonials',
    keyMetrics: 'Listing inquiries, buyer leads, seller consultations, referral rate',
    commonMistakes: [
      'Only posting listings (no education or personal brand)',
      'Low-quality photos/videos of properties',
      'Not geo-targeting ads to local area',
      'Missing Facebook Group strategy for community',
    ],
    expectedResults: 'With consistent effort: 2-5 inbound leads/week at 60 days, 200-500 new followers/month',
  },
  {
    id: 'fitness',
    name: 'Fitness / Wellness',
    emoji: '💪',
    topPlatforms: ['Instagram', 'TikTok', 'YouTube', 'Facebook'],
    contentStyle: 'Workout videos, transformation stories, nutrition tips, day-in-the-life, Q&A',
    keyMetrics: 'New client sign-ups, class bookings, online program sales, community growth',
    commonMistakes: [
      'Before/after content without proper context or permission',
      'Only promoting services without providing free value',
      'Not building an email list from social traffic',
      'Ignoring local search and Google Business Profile',
    ],
    expectedResults: 'With consistent effort: 3-8 new clients/month from social at 90 days, 500-1500 new followers/month',
  },
  {
    id: 'food',
    name: 'Food & Beverage',
    emoji: '🍽',
    topPlatforms: ['Instagram', 'TikTok', 'Facebook', 'Pinterest'],
    contentStyle: 'Recipe videos, behind-the-scenes kitchen, sourcing stories, team spotlights, limited-time offers',
    keyMetrics: 'In-store footfall, online orders, event bookings, catering inquiries',
    commonMistakes: [
      'Blurry or dark food photography',
      'Not using geo-tags and local hashtags',
      'Ignoring UGC from happy customers',
      'No seasonal content calendar',
    ],
    expectedResults: 'With consistent effort: 25-50% increase in foot traffic from social within 90 days',
  },
  {
    id: 'professional',
    name: 'Professional Services',
    emoji: '⚖',
    topPlatforms: ['LinkedIn', 'Facebook', 'YouTube', 'Google Business'],
    contentStyle: 'Educational content, FAQ videos, case studies (anonymised), thought leadership, awards/credentials',
    keyMetrics: 'Consultation bookings, referral inquiries, website traffic, email list growth',
    commonMistakes: [
      'Too formal/corporate tone that lacks personality',
      'Not showcasing the human side of the team',
      'No clear CTA on posts',
      'Ignoring Google My Business optimisation',
    ],
    expectedResults: 'With consistent effort: 5-15 consultation requests/month at 90 days',
  },
  {
    id: 'construction',
    name: 'Construction / Trades',
    emoji: '🔨',
    topPlatforms: ['Facebook', 'Instagram', 'YouTube', 'Houzz'],
    contentStyle: 'Project transformations, time-lapse builds, team/crew content, client testimonials, process explainers',
    keyMetrics: 'Quote requests, project bookings, referral rate, local search visibility',
    commonMistakes: [
      'Not documenting projects as they happen (great content)',
      'No video of finished work with client testimonial',
      'Ignoring Google Local Service Ads',
      'No reviews strategy on Google/Facebook',
    ],
    expectedResults: 'With consistent effort: 10-20 new quote requests/month at 90 days',
  },
  {
    id: 'beauty',
    name: 'Beauty / Lifestyle',
    emoji: '💄',
    topPlatforms: ['Instagram', 'TikTok', 'Pinterest', 'YouTube'],
    contentStyle: 'Transformations, tutorials, product reviews, GRWM (Get Ready With Me), behind the chair',
    keyMetrics: 'Appointment bookings, product sales, rebooking rate, follower growth',
    commonMistakes: [
      'Not capturing before/after transformations consistently',
      'Only posting final looks (skip the process)',
      'Not encouraging clients to tag and share',
      'Underutilising Instagram Reels for discovery',
    ],
    expectedResults: 'With consistent effort: 30-50 new bookings/month from social at 90 days',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    emoji: '🏥',
    topPlatforms: ['Facebook', 'Instagram', 'LinkedIn', 'YouTube'],
    contentStyle: 'Educational health tips, FAQs, team introductions, patient journey (with consent), community events',
    keyMetrics: 'Appointment bookings, new patient inquiries, referral partnerships, email subscribers',
    commonMistakes: [
      'Sharing patient information without strict consent protocols',
      'Too clinical/jargon-heavy content for lay audiences',
      'Not building trust through team visibility',
      'Ignoring Google ads for high-intent searches',
    ],
    expectedResults: 'With consistent effort: 15-30 new patient inquiries/month at 90 days',
  },
]

export const TRENDING_2025 = [
  {
    title: 'Short-Form Video Dominance',
    icon: '▶',
    color: 'border-bms-cyan/30',
    description: 'Reels, TikToks, and YouTube Shorts now account for over 60% of all social media time spent. The optimal length is 15-30 seconds with a strong hook in the first 2 seconds.',
    tactics: [
      'Hook viewers with a bold statement or question in frame 1',
      'Add captions — 85% of videos are watched without sound',
      'Post 3-5x/week minimum to feed the algorithm',
      'Repurpose one video across TikTok, Reels, Shorts, and LinkedIn',
    ],
    roi: 'Brands using short-form video see 49% faster revenue growth than those who don\'t',
  },
  {
    title: 'UGC (User Generated Content)',
    icon: '📸',
    color: 'border-purple-500/30',
    description: 'UGC converts at 4x higher rates than brand-created content. Consumers trust other consumers, and UGC provides authentic social proof at scale.',
    tactics: [
      'Create a branded hashtag and actively promote it',
      'Run monthly "tag us and win" giveaways',
      'Reach out to happy customers directly for video testimonials',
      'Reshare and credit UGC creators in your Stories and feed',
    ],
    roi: 'UGC reduces content creation costs by 50% while increasing conversions 4.5x',
  },
  {
    title: 'Behind-the-Scenes Content',
    icon: '🎬',
    color: 'border-emerald-500/30',
    description: 'Authenticity is the currency of 2025 social media. Behind-the-scenes content builds trust and connection faster than polished marketing ever could.',
    tactics: [
      'Document your process, not just the finished result',
      'Show the team — faces build trust',
      'Share failures and lessons alongside wins',
      'Use Stories for real-time behind-the-scenes moments',
    ],
    roi: 'BTS content generates 3x more comments and 2x more shares than polished content',
  },
  {
    title: 'Educational / How-To Content',
    icon: '📚',
    color: 'border-amber-500/30',
    description: 'The "teach to attract" model: brands that educate their audience build authority, trust, and an audience that comes back repeatedly — and eventually buys.',
    tactics: [
      'Create a "101 series" for beginners in your niche',
      'Turn FAQs into short video answers',
      'Use carousels on Instagram/LinkedIn for step-by-step guides',
      'Produce "myth-busting" content in your industry',
    ],
    roi: 'Educational content drives 3x more leads than product-focused content',
  },
  {
    title: 'Social Proof & Testimonials',
    icon: '⭐',
    color: 'border-pink-500/30',
    description: '92% of consumers read reviews before purchasing. Video testimonials and case studies are the highest-converting content type for any service business.',
    tactics: [
      'Create a simple system to collect video testimonials post-purchase',
      'Screenshot and share Google/Facebook reviews in Stories',
      'Build "results highlight" content from client outcomes',
      'Use before/after format with client permission',
    ],
    roi: 'Video testimonials increase conversion rates by 80% vs text-only testimonials',
  },
  {
    title: 'Community Building',
    icon: '👥',
    color: 'border-bms-cyan/30',
    description: 'Social media is shifting from broadcasting to community. Brands building private communities (Facebook Groups, Discord, newsletters) have far stronger retention than follower counts alone.',
    tactics: [
      'Launch a free Facebook Group around a shared interest',
      'Create a "VIP client" community for referrals',
      'Engage daily with comments — respond within 1 hour when possible',
      'Host weekly Lives or Q&A sessions inside the community',
    ],
    roi: 'Community members spend 19% more than non-community customers',
  },
  {
    title: 'AI-Assisted Content Strategy',
    icon: '🤖',
    color: 'border-purple-500/30',
    description: 'AI tools like Claude, ChatGPT, and Midjourney are being used by top brands to scale content production — but the winning brands use AI for drafts and humans for final touch.',
    tactics: [
      'Use AI for captions, hooks, and hashtag sets at scale',
      'Generate 30 post ideas in 5 minutes with a good prompt',
      'Repurpose blog posts into social content automatically',
      'A/B test AI-generated vs human copy to find what converts',
    ],
    roi: 'Brands using AI for content see 40% reduction in production time with 15% improvement in engagement',
  },
]

export const RESULTS_TABLE = [
  {
    level: 'Low',
    effort: '1-2 posts/week',
    badge: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    followersPerMonth: '50 – 200',
    engagementRate: '1% – 2%',
    leadGen: '1 – 5 leads/month',
    revenueImpact: 'Minimal — mostly brand awareness',
    timeToResults: '6-12 months',
  },
  {
    level: 'Medium',
    effort: '3-5 posts/week + Stories',
    badge: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    followersPerMonth: '200 – 800',
    engagementRate: '2% – 5%',
    leadGen: '5 – 20 leads/month',
    revenueImpact: 'Moderate — consistent inbound inquiries',
    timeToResults: '3-6 months',
  },
  {
    level: 'High',
    effort: 'Daily posts + Stories + Reels',
    badge: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    followersPerMonth: '500 – 3,000+',
    engagementRate: '4% – 12%',
    leadGen: '20 – 100+ leads/month',
    revenueImpact: 'Significant — social becomes primary lead channel',
    timeToResults: '1-3 months',
  },
]

export const INDUSTRY_BENCHMARKS = [
  { industry: 'E-commerce', avgEngagement: '1.8%', followerGrowth: '2-4%/mo', conversionRate: '1-3%', adROAS: '3-6x' },
  { industry: 'SaaS/Tech', avgEngagement: '2.4%', followerGrowth: '1-3%/mo', conversionRate: '2-5%', adROAS: '4-8x' },
  { industry: 'Hospitality', avgEngagement: '3.2%', followerGrowth: '3-6%/mo', conversionRate: '5-15%', adROAS: '5-10x' },
  { industry: 'Real Estate', avgEngagement: '2.1%', followerGrowth: '2-5%/mo', conversionRate: '1-3%', adROAS: '8-20x' },
  { industry: 'Fitness/Wellness', avgEngagement: '4.0%', followerGrowth: '4-8%/mo', conversionRate: '3-8%', adROAS: '4-7x' },
  { industry: 'Food & Beverage', avgEngagement: '3.8%', followerGrowth: '3-7%/mo', conversionRate: '8-20%', adROAS: '3-5x' },
  { industry: 'Professional Services', avgEngagement: '1.9%', followerGrowth: '1-3%/mo', conversionRate: '5-15%', adROAS: '10-30x' },
  { industry: 'Beauty/Lifestyle', avgEngagement: '5.2%', followerGrowth: '5-10%/mo', conversionRate: '2-6%', adROAS: '4-8x' },
]

export const MARKETING_SKILLS = [
  {
    id: 'seo-audit',
    name: 'SEO Audit',
    icon: '🔍',
    description: 'Comprehensive on-page and technical SEO analysis to identify quick wins and long-term improvements for search rankings.',
    whenToUse: 'When you want to improve organic search visibility and drive consistent free traffic to your website.',
    category: 'Growth',
    categoryColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  },
  {
    id: 'page-cro',
    name: 'Page CRO',
    icon: '📈',
    description: 'Conversion Rate Optimisation analysis for landing pages, product pages, and key funnels to maximise value from existing traffic.',
    whenToUse: 'When you have traffic but not enough conversions. A 1% improvement in CRO can double your revenue.',
    category: 'Conversion',
    categoryColor: 'bg-bms-cyan/10 text-bms-cyan border-bms-cyan/20',
  },
  {
    id: 'copywriting',
    name: 'Copywriting',
    icon: '✍',
    description: 'Persuasive copy for ads, landing pages, emails, and social posts using proven frameworks like AIDA, PAS, and BAB.',
    whenToUse: 'When your content isn\'t converting or you need fresh ad copy that speaks directly to your audience\'s pain points.',
    category: 'Content',
    categoryColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  },
  {
    id: 'social-content',
    name: 'Social Content',
    icon: '📱',
    description: 'Platform-specific content creation for Instagram, TikTok, LinkedIn, and more. Includes captions, hooks, and content calendar planning.',
    whenToUse: 'When you need a consistent flow of quality content that drives engagement and grows your audience on social platforms.',
    category: 'Social',
    categoryColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
  },
  {
    id: 'cold-email',
    name: 'Cold Email',
    icon: '📧',
    description: 'High-converting cold outreach sequences with personalisation at scale. Includes subject lines, openers, CTAs, and follow-ups.',
    whenToUse: 'When you want to generate B2B leads proactively without relying on inbound traffic.',
    category: 'Outreach',
    categoryColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  },
  {
    id: 'email-sequence',
    name: 'Email Sequence',
    icon: '📬',
    description: 'Automated nurture sequences for new leads, welcome flows, abandoned cart recovery, and post-purchase upsell journeys.',
    whenToUse: 'To monetise your email list and build automated revenue streams that work 24/7.',
    category: 'Automation',
    categoryColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  },
  {
    id: 'paid-ads',
    name: 'Paid Ads',
    icon: '💰',
    description: 'Meta Ads, Google Ads, and TikTok Ads strategy including audience targeting, creative direction, budget allocation, and optimisation.',
    whenToUse: 'When you\'re ready to scale and want predictable, trackable ROI from your marketing budget.',
    category: 'Paid',
    categoryColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  },
  {
    id: 'ab-test-setup',
    name: 'A/B Test Setup',
    icon: '🧪',
    description: 'Structured split testing frameworks for ads, landing pages, email subject lines, and CTAs to make data-driven decisions.',
    whenToUse: 'When you want to stop guessing and start optimising based on real performance data.',
    category: 'Optimisation',
    categoryColor: 'bg-bms-cyan/10 text-bms-cyan border-bms-cyan/20',
  },
  {
    id: 'content-strategy',
    name: 'Content Strategy',
    icon: '🗺',
    description: 'Full content marketing strategy including audience mapping, content pillars, channel mix, and 90-day content roadmap.',
    whenToUse: 'When you need a clear, structured plan for what to create, where to publish it, and why it\'ll work for your audience.',
    category: 'Strategy',
    categoryColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  },
  {
    id: 'analytics-tracking',
    name: 'Analytics Tracking',
    icon: '📊',
    description: 'GA4 setup, Meta Pixel, conversion tracking, and custom dashboard creation to measure what actually matters.',
    whenToUse: 'When you\'re flying blind on your marketing performance and need proper attribution and reporting.',
    category: 'Analytics',
    categoryColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  },
  {
    id: 'brand-voice',
    name: 'Brand Voice',
    icon: '🎙',
    description: 'Define your brand\'s personality, tone of voice, messaging pillars, and style guide for consistent communication.',
    whenToUse: 'When your brand sounds different on every channel and you need a cohesive, recognisable identity.',
    category: 'Branding',
    categoryColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
  },
  {
    id: 'influencer-brief',
    name: 'Influencer Brief',
    icon: '🌟',
    description: 'Professional creator briefs for influencer partnerships, including deliverables, messaging guidelines, and performance expectations.',
    whenToUse: 'When you want to leverage influencer marketing without losing control of your brand message.',
    category: 'Partnerships',
    categoryColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  },
]
