export type Platform = {
  id: string
  name: string
  emoji: string
  color: string
  bg: string
  border: string
  bestFor: string[]
  industries: string[]
  postingFrequency: string
  peakTimes: string[]
  avgEngagement: string
  contentTypes: string[]
  whatWorksNow: string[]
  avoidThis: string[]
  benchmarks: { metric: string; value: string }[]
}

export const PLATFORMS: Platform[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    emoji: '📸',
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
    border: 'border-pink-500/20',
    bestFor: ['Visual storytelling', 'Brand awareness', 'Product showcase', 'Lifestyle content'],
    industries: ['E-commerce', 'Beauty & Fashion', 'Food & Beverage', 'Fitness', 'Interior Design', 'Travel'],
    postingFrequency: '1–2 feed posts/day + 5–10 Stories',
    peakTimes: ['Mon–Fri 6–9am', 'Tue–Fri 11am–1pm', 'Mon–Fri 7–9pm'],
    avgEngagement: '0.5–3% (Reels can hit 5–10%)',
    contentTypes: ['Reels (90s max)', 'Carousels (10 slides)', 'Stories (24hr)', 'Static posts', 'Live'],
    whatWorksNow: [
      'Reels get 3× more reach than static posts',
      'Carousels drive 3× more shares & saves',
      'Behind-the-scenes content outperforms polished ads',
      'UGC (user-generated content) builds trust instantly',
      'Trending audio boosts Reels discoverability',
      'Polls & questions in Stories increase engagement',
      'Collab posts with micro-influencers reach new audiences',
    ],
    avoidThis: [
      'Posting links in captions (Instagram penalises)',
      'Inconsistent posting schedule',
      'No CTA in captions',
      'Ignoring comments for 24h+ after posting',
    ],
    benchmarks: [
      { metric: 'Avg engagement rate', value: '1.22%' },
      { metric: 'Reels avg reach', value: '3–5× vs static' },
      { metric: 'Best follower growth', value: '100–300/month (1k start)' },
      { metric: 'Story view rate', value: '5–7% of followers' },
      { metric: 'Ad CTR (avg)', value: '0.5–1.5%' },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    emoji: '🎵',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
    bestFor: ['Viral reach', 'Brand discovery', 'Younger demographics', 'Entertainment', 'Education'],
    industries: ['FMCG', 'Beauty', 'Entertainment', 'Food', 'Fashion', 'Education', 'Finance (FinTok)'],
    postingFrequency: '1–4 videos/day for growth phase',
    peakTimes: ['Tue–Thu 7–9am', 'Tue–Thu 12–3pm', 'Tue–Thu 7–11pm'],
    avgEngagement: '5–10% (highest of all platforms)',
    contentTypes: ['Short videos (15–60s)', 'Long videos (3–10min)', 'Duets', 'Stitches', 'Live'],
    whatWorksNow: [
      'Hook in first 1–2 seconds is everything',
      'Trending sounds × your niche = algorithm boost',
      'Raw/authentic content outperforms over-produced',
      'Comment replies as videos build loyalty',
      'Educational content ("TikTok teaches me") goes viral',
      'Series content keeps viewers coming back',
      'Posting 3–4× daily during growth = fastest results',
    ],
    avoidThis: [
      'Posting videos with competitor watermarks (penalised)',
      'Ignoring trending sounds',
      'Over-polished corporate content',
      'Deleting videos (hurts algorithm)',
    ],
    benchmarks: [
      { metric: 'Avg engagement rate', value: '5.96%' },
      { metric: 'Organic reach potential', value: 'Unlimited (For You Page)' },
      { metric: 'Fastest growth platform', value: '0–10k in 30 days possible' },
      { metric: 'Ad CPM', value: '£5–10 avg' },
      { metric: 'Conversion rate (ecomm)', value: '1–3%' },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    emoji: '💼',
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    bestFor: ['B2B leads', 'Thought leadership', 'Recruitment', 'Professional networking', 'SaaS'],
    industries: ['SaaS/Tech', 'Consulting', 'Finance', 'HR & Recruitment', 'Legal', 'Professional Services', 'Manufacturing'],
    postingFrequency: '3–5 posts/week',
    peakTimes: ['Tue–Thu 7–8am', 'Tue–Thu 12pm', 'Tue–Thu 5–6pm'],
    avgEngagement: '2–5% (highest quality leads)',
    contentTypes: ['Text posts (with line breaks)', 'Carousels (PDF docs)', 'Articles', 'Short videos', 'Polls', 'Newsletter'],
    whatWorksNow: [
      'Personal story posts get 3–5× more reach than company pages',
      'Carousels (slide PDFs) are the #1 format for saves',
      'Controversial/contrarian takes drive comments',
      'Employee advocacy posts reach 8× more people',
      'Polls drive huge engagement with minimal effort',
      'Short video (30–90s) is fastest-growing format on LI',
      '"I failed at X. Here is what I learned." posts go viral',
    ],
    avoidThis: [
      'Putting links in posts (put in first comment instead)',
      'Posting about politics/religion',
      'Pitching in DMs immediately',
      'Only sharing company news',
    ],
    benchmarks: [
      { metric: 'Avg engagement rate', value: '2–5%' },
      { metric: 'B2B lead quality', value: 'Highest of all platforms' },
      { metric: 'Ad conversion rate', value: '2.74% (industry leading B2B)' },
      { metric: 'Organic post reach', value: '5–10% of connections (declining)' },
      { metric: 'InMail open rate', value: '57% (vs 22% email)' },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    emoji: '👥',
    color: 'text-blue-500',
    bg: 'bg-blue-600/10',
    border: 'border-blue-600/20',
    bestFor: ['Community building', 'Local businesses', 'Older demographics (35+)', 'Events', 'Facebook Ads'],
    industries: ['Local Services', 'Real Estate', 'Healthcare', 'Hospitality', 'Retail', 'Non-profits', 'Trades'],
    postingFrequency: '1–2 posts/day',
    peakTimes: ['Wed 11am–1pm', 'Thu–Fri 1–4pm', 'Sat–Sun 12–1pm'],
    avgEngagement: '0.07–0.15% (organic reach very low, 2–5% of followers)',
    contentTypes: ['Native video', 'Groups posts', 'Events', 'Stories', 'Live', 'Reels'],
    whatWorksNow: [
      'Facebook Groups outperform Pages 10× for organic reach',
      'Native video gets 10× more reach than YouTube links',
      'Facebook Ads still best ROI for targeting specific demographics',
      'Events get free organic reach when people click "interested"',
      'Facebook Marketplace for local product selling',
      'Live video gets 6× more interactions than regular video',
    ],
    avoidThis: [
      'Posting external links (massive organic reach penalty)',
      'Relying on Page organic reach (it is essentially dead)',
      'Using stock photos (engagement tanks)',
      'Boosting posts without proper audience targeting',
    ],
    benchmarks: [
      { metric: 'Page organic reach', value: '2–5% of page likes' },
      { metric: 'Group organic reach', value: '20–40% of members' },
      { metric: 'Ad CTR', value: '0.9% avg (Meta)' },
      { metric: 'CPM', value: '£4–15 (Meta Ads)' },
      { metric: 'ROAS (ecomm)', value: '2–4× avg with good creative' },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    emoji: '▶️',
    color: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/20',
    bestFor: ['SEO & discoverability', 'Long-form education', 'Product demos', 'Trust building', 'Passive growth'],
    industries: ['Education', 'SaaS', 'Finance', 'Fitness', 'DIY/Trades', 'Tech', 'Cooking', 'Real Estate'],
    postingFrequency: '1–3 videos/week (Shorts: daily)',
    peakTimes: ['Thu–Sat 12–4pm', 'Thu–Sat 8–11pm'],
    avgEngagement: '1–4% (measured by views/subscribers)',
    contentTypes: ['Long-form video (8–20min)', 'Shorts (under 60s)', 'Live streams', 'Community posts'],
    whatWorksNow: [
      'Shorts drive subscriber growth faster than long-form',
      'Titles with numbers and "how to" consistently outperform',
      'Thumbnails with faces get 38% more clicks',
      'Chapters/timestamps increase watch time (YouTube rewards)',
      '8–12 min videos hit ad revenue sweet spot',
      'Pinned comment with key links drives conversion',
      'End screen cards boost subscription rate by 80%',
    ],
    avoidThis: [
      'Skipping SEO in title/description/tags',
      'Posting inconsistently (algorithm penalises gaps)',
      'No thumbnail custom image',
      'Talking for 5 mins before getting to the point',
    ],
    benchmarks: [
      { metric: 'Avg view duration', value: '35–50% of video length' },
      { metric: 'Good CTR (thumbnails)', value: '4–10%' },
      { metric: 'Subscriber growth (consistent)', value: '2–5% monthly' },
      { metric: 'Shorts views potential', value: 'Millions with right hook' },
      { metric: 'CPM (ad revenue)', value: '£1–15 depending on niche' },
    ],
  },
  {
    id: 'x',
    name: 'X (Twitter)',
    emoji: '𝕏',
    color: 'text-gray-300',
    bg: 'bg-gray-500/10',
    border: 'border-gray-500/20',
    bestFor: ['Real-time marketing', 'Tech/startup community', 'Personal brand', 'Thought leadership', 'News commentary'],
    industries: ['SaaS/Tech', 'Crypto/Web3', 'Media', 'Politics', 'Finance', 'Journalism', 'Marketing agencies'],
    postingFrequency: '3–10 posts/day',
    peakTimes: ['Weekdays 8–10am', 'Weekdays 12–1pm', 'Weekdays 5–6pm'],
    avgEngagement: '0.5–1% (but reach can be enormous with virality)',
    contentTypes: ['Short posts (<280 chars)', 'Threads', 'Polls', 'Spaces (audio live)', 'Replies/Quote posts'],
    whatWorksNow: [
      'Threads consistently outperform single tweets',
      'Contrarian/hot takes drive massive engagement',
      'Replying to viral posts = free exposure',
      'Build-in-public content drives loyal following',
      'X Premium boosts reply visibility (pay-to-play)',
      'Long-form posts (Premium subscribers) do well in tech',
    ],
    avoidThis: [
      'Expecting consistent organic reach (very algorithm-dependent)',
      'Soft brand voice (X rewards bold opinions)',
      'Not engaging in threads of popular posts',
    ],
    benchmarks: [
      { metric: 'Good engagement rate', value: '0.5–1%' },
      { metric: 'Viral potential', value: 'High (trends move fast)' },
      { metric: 'Best for', value: 'Tech/startup audiences' },
      { metric: 'Daily active users UK', value: '22 million' },
    ],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    emoji: '📌',
    color: 'text-red-400',
    bg: 'bg-red-500/8',
    border: 'border-red-500/20',
    bestFor: ['Evergreen content', 'Product discovery', 'SEO', 'Female-skewed audiences', 'Inspiration content'],
    industries: ['Interior Design', 'Fashion', 'Food & Recipes', 'Weddings', 'DIY/Crafts', 'Health & Wellness', 'Travel', 'E-commerce'],
    postingFrequency: '5–15 pins/day (mix fresh + repins)',
    peakTimes: ['Sat 8–11pm', 'Fri 3pm', 'Mon–Thu 2–4pm, 8–11pm'],
    avgEngagement: 'Measured by saves, clicks (high purchase intent)',
    contentTypes: ['Static pins (2:3 ratio)', 'Idea pins (video)', 'Product pins', 'Story pins'],
    whatWorksNow: [
      'Pins have 3–6 month lifespan (unlike other platforms)',
      'Keyword-rich descriptions act as SEO for Google too',
      'Video pins get 3× more impressions',
      'Product pins with prices drive direct sales',
      'Seasonal content (plan 45 days ahead)',
    ],
    avoidThis: [
      'Horizontal images (portrait 2:3 always wins)',
      'No text overlay on images',
      'Ignoring keywords in pin descriptions',
    ],
    benchmarks: [
      { metric: 'Purchase intent', value: '89% use Pinterest for purchase inspiration' },
      { metric: 'Pin lifespan', value: '3–6 months (vs hrs on other platforms)' },
      { metric: 'Traffic potential', value: 'High referral traffic to website' },
      { metric: 'Avg order value', value: '50% higher than other social platforms' },
    ],
  },
]
